version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_data:/data

volumes:
  redis_data:
  redisinsight_data: